name: Cosmetics
main: com.wolfie.cosmetics.main
version: 1.0
author: IAmTheWolfie
commands:
   cosmetics:
      description: Opens up the Cosmetics menu.
      usage: /<command>
      permission: <plugin name>.openMenu
      permission-message: You don't have <permission>