name: Cosmetics
main: com.wolfie.cosmetics.main.Main
version: 1.0
author: IAmTheWolfie
commands:
   cosmetics:
      description: Opens up the Cosmetics menu.
      permission: cosmetics.openMenu
      permission-message: You don't have <permission>